# Generated by Django 3.1 on 2020-08-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='s_published',
            new_name='is_published',
        ),
    ]
